# Generated by Django 5.1.3 on 2024-11-29 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_variants_product_variant_subvariant_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='ProductImage',
        ),
    ]
